import { createFileRoute } from "@tanstack/react-router";
import { PageHeader } from "@/components/page-header";
import { pageHead } from "@/lib/seo";
import { useCmsContent } from "@/lib/cms";
import { events as fallbackEvents } from "@/lib/content";

export const Route = createFileRoute("/eventos")({ head: () => pageHead({ path: "/eventos", title: "Eventos", description: "Próximos encuentros, concentraciones y actos de la Plataforma Dorada." }), component: Page });
function dateParts(date:string){const d=new Date(`${date}T12:00:00`); return {day:Number.isNaN(d.getTime())?date.slice(-2):String(d.getDate()).padStart(2,"0"), month:Number.isNaN(d.getTime())?"":d.toLocaleDateString("es-ES",{month:"short"}).replace(".","").toUpperCase()};}
function List({past, events}:{past:boolean;events:any[]}){const list=events.filter(e=>{const isPast=e.date?new Date(`${e.date}T23:59:59`).getTime()<Date.now():Boolean(e.past);return isPast===past;}); return <ul className="mt-6 space-y-4">{list.map((e,i)=>{const p=e.date?dateParts(e.date):{day:e.day,month:e.month}; return <li key={e.id??i} className="glass-panel overflow-hidden rounded-3xl p-5"><div className="grid gap-5 md:grid-cols-[auto_1fr_280px] md:items-center"><div className="grid size-16 shrink-0 place-items-center rounded-2xl bg-primary text-center text-primary-foreground"><span className="font-display text-xl font-semibold leading-none">{p.day}<br/><span className="text-xs">{p.month}</span></span></div><div><p className="font-display text-lg font-semibold">{e.title}</p><p className="text-sm text-muted-foreground">{[e.place,e.city,e.time].filter(Boolean).join(" · ")}</p>{e.description&&<p className="mt-2 text-sm text-muted-foreground whitespace-pre-line">{e.description}</p>}{e.url&&<a href={e.url} target="_blank" rel="noreferrer" className="mt-3 inline-block text-sm font-semibold text-primary underline">Más información</a>}</div>{e.documentUrl&&<a href={e.documentUrl} target="_blank" rel="noreferrer" className="group block overflow-hidden rounded-2xl border border-border bg-muted p-2 text-center"><img src={e.previewUrl || e.documentUrl} alt={e.documentName?`Documento del evento ${e.title}`:`Documento del evento ${e.title}`} className="mx-auto max-h-48 w-full object-contain" loading="lazy"/><span className="mt-2 block text-xs font-semibold text-primary">Abrir / descargar cartel</span></a>}</div></li>})}</ul>}
function Page(){const cms=useCmsContent(); const events=cms?.eventos?.length?cms.eventos:fallbackEvents.map((e,i)=>({id:String(i),title:e.title,date:"",time:"",place:e.place,city:"",description:"",url:"",documentUrl:"",documentName:"",past:e.past})); return <><PageHeader eyebrow="Agenda" title="Eventos" lead="Encuéntranos en tu ciudad. La agenda se actualiza automáticamente desde el equipo de la Plataforma."/><section className="mx-auto w-full max-w-6xl px-4 pb-10 sm:px-6"><h2 className="font-display text-3xl">Próximos eventos</h2><List past={false} events={events}/></section><section className="mx-auto w-full max-w-6xl px-4 pb-14 sm:px-6"><h2 className="font-display text-3xl">Eventos realizados</h2><List past events={events}/></section></>;}
