/**
 * Plataforma Dorada — CMS público + backoffice.
 * Noticias, eventos, recursos y propuestas de redes sociales.
 */
function doGet(e) {
  var params=(e&&e.parameter)||{};
  if(params.view==='admin') return HtmlService.createHtmlOutputFromFile('admin').setTitle('Plataforma Dorada · Backoffice').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
  var callback=/^[A-Za-z_$][\w$.]*$/.test(params.callback||'')?params.callback:'';
  var action=params.action||'count';
  var payload=action==='content'?getPublicContent_():action==='public'?getPublicStats_():{adhesiones:countAllAdhesions_(),actualizado:new Date().toISOString()};
  return outputJson_(payload,callback);
}
function doPost(e){
  try{
    var body=JSON.parse((e&&e.postData&&e.postData.contents)||'{}');
    if(body.action==='proposal'){
      return outputJson_(saveProposalPublic_(body),'');
    }
    return outputJson_({error:'Acción no válida'},'');
  }catch(err){ return outputJson_({error:String(err&&err.message||err)},''); }
}
function outputJson_(payload,callback){var json=JSON.stringify(payload);return callback?ContentService.createTextOutput(callback+'('+json+')').setMimeType(ContentService.MimeType.JAVASCRIPT):ContentService.createTextOutput(json).setMimeType(ContentService.MimeType.JSON);}
function countAllAdhesions_(){var ss=SpreadsheetApp.getActiveSpreadsheet(),sheet=ss.getSheetByName('Firmantes');if(sheet)return Math.max(0,sheet.getLastRow()-1);return 0;}
function ensureSheetHeaders_(name,headers){var ss=SpreadsheetApp.getActiveSpreadsheet(),sheet=ss.getSheetByName(name);if(!sheet){sheet=ss.insertSheet(name);sheet.getRange(1,1,1,headers.length).setValues([headers]);sheet.setFrozenRows(1);return sheet;}var current=sheet.getRange(1,1,Math.max(sheet.getLastColumn(),headers.length),1).getDisplayValues().map(function(r){return r[0];}); // no-op placeholder
var last=sheet.getLastColumn();var existing=last?sheet.getRange(1,1,1,last).getDisplayValues()[0]:[];for(var i=existing.length;i<headers.length;i++)sheet.getRange(1,i+1).setValue(headers[i]);sheet.setFrozenRows(1);return sheet;}
function getOrCreateSheet_(name,headers){return ensureSheetHeaders_(name,headers);}
function readNews_(){var s=getOrCreateSheet_('NoticiasWeb',['id','titulo','medio','fecha','url','resumen','publicada','creada']),n=s.getLastRow();if(n<2)return [];return s.getRange(2,1,n-1,8).getDisplayValues().filter(function(r){return String(r[6]).toLowerCase()!=='no';}).map(function(r){return{id:r[0],title:r[1],media:r[2],date:r[3],url:r[4],summary:r[5]};}).reverse();}
function eventHeaders_(){return ['id','titulo','fecha','hora','lugar','ciudad','descripcion','url','documentoNombre','documentoUrl','documentoId','publicada','creada'];}
function readEvents_(){var s=getOrCreateSheet_('EventosWeb',eventHeaders_()),n=s.getLastRow();if(n<2)return [];var v=s.getRange(2,1,n-1,eventHeaders_().length).getDisplayValues();return v.filter(function(r){return String(r[11]).toLowerCase()!=='no';}).map(function(r){return{id:r[0],title:r[1],date:r[2],time:r[3],place:r[4],city:r[5],description:r[6],url:r[7],documentName:r[8],documentUrl:r[9]};}).reverse();}
function readResources_(){var s=getOrCreateSheet_('RecursosWeb',['id','titulo','categoria','descripcion','archivo','url','creado']),n=s.getLastRow();if(n<2)return [];return s.getRange(2,1,n-1,7).getDisplayValues().map(function(r){return{id:r[0],title:r[1],category:r[2],description:r[3],filename:r[4],url:r[5]};}).reverse();}
function proposalHeaders_(){return ['id','tipo','titulo','artista','texto','proponente','publicada','creada'];}
function readProposals_(){var s=getOrCreateSheet_('PropuestasWeb',proposalHeaders_()),n=s.getLastRow();if(n<2)return {canciones:[],frases:[],todas:[]};var v=s.getRange(2,1,n-1,8).getDisplayValues();var all=v.map(function(r){return{id:r[0],type:r[1],title:r[2],artist:r[3],text:r[4],proposer:r[5],published:String(r[6]).toLowerCase()!=='no',created:r[7]};}).reverse();return {canciones:all.filter(function(x){return x.type==='cancion'&&x.published;}).map(function(x){return{x:x.title,artist:x.artist};}),frases:all.filter(function(x){return x.type==='frase'&&x.published;}).map(function(x){return{text:x.text,name:x.proposer};}),todas:all};}
function getPublicContent_(){var p=readProposals_();return{noticias:readNews_(),recursos:readResources_(),eventos:readEvents_(),canciones:p.canciones,frases:p.frases,actualizado:new Date().toISOString()};}
function getDriveFolder_(){var props=PropertiesService.getScriptProperties(),id=props.getProperty('RECURSOS_FOLDER_ID');if(id)return DriveApp.getFolderById(id);var fs=DriveApp.getFoldersByName('Plataforma Dorada - Recursos'),f=fs.hasNext()?fs.next():DriveApp.createFolder('Plataforma Dorada - Recursos');props.setProperty('RECURSOS_FOLDER_ID',f.getId());return f;}
function checkPassword(password){var expected=PropertiesService.getScriptProperties().getProperty('BACKOFFICE_PASSWORD');if(!expected)throw new Error('El backoffice aún no tiene contraseña configurada.');if(String(password||'')!==expected)throw new Error('Contraseña incorrecta.');return true;}
function getPublicContent(){return getPublicContent_();}
function getBackofficeContent(){var c=getPublicContent_();c.propuestas=readProposals_().todas;return c;}
function setupBackoffice(){getOrCreateSheet_('NoticiasWeb',['id','titulo','medio','fecha','url','resumen','publicada','creada']);getOrCreateSheet_('RecursosWeb',['id','titulo','categoria','descripcion','archivo','url','creado']);getOrCreateSheet_('EventosWeb',eventHeaders_());getOrCreateSheet_('PropuestasWeb',proposalHeaders_());getDriveFolder_();return 'Backoffice preparado';}
function saveNews(data){assertAdmin_(data&&data.password);var s=getOrCreateSheet_('NoticiasWeb',['id','titulo','medio','fecha','url','resumen','publicada','creada']),id=Utilities.getUuid();s.appendRow([id,String(data.title||'').trim(),String(data.media||'').trim(),String(data.date||'').trim(),String(data.url||'').trim(),String(data.summary||'').trim(),data.published===false?'No':'Sí',new Date().toISOString()]);return{ok:true,id:id};}
function saveResource(data){assertAdmin_(data&&data.password);if(!data.fileName||!data.base64)throw new Error('Falta el archivo.');var bytes=Utilities.base64Decode(data.base64);if(bytes.length>10*1024*1024)throw new Error('El archivo supera el límite de 10 MB.');var file=getDriveFolder_().createFile(Utilities.newBlob(bytes,data.mimeType||'application/octet-stream',data.fileName));file.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW);var s=getOrCreateSheet_('RecursosWeb',['id','titulo','categoria','descripcion','archivo','url','creado']),id=Utilities.getUuid(),url='https://drive.google.com/uc?export=download&id='+file.getId();s.appendRow([id,String(data.title||data.fileName).trim(),String(data.category||'Materiales').trim(),String(data.description||'').trim(),data.fileName,url,new Date().toISOString()]);return{ok:true,id:id,url:url};}
function findRowById_(sheet,id){var v=sheet.getDataRange().getValues();for(var i=1;i<v.length;i++)if(String(v[i][0])===String(id))return i+1;return -1;}
function saveEvent(data){assertAdmin_(data&&data.password);var title=String(data.title||'').trim(),date=String(data.date||'').trim();if(!title)throw new Error('El título del evento es obligatorio.');if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new Error('La fecha del evento no es válida.');var s=getOrCreateSheet_('EventosWeb',eventHeaders_()),id=String(data.id||'').trim(),row=id?findRowById_(s,id):-1;if(row<0){id=Utilities.getUuid();row=s.getLastRow()+1;}var oldId=row>0?String(s.getRange(row,11).getDisplayValue()||''):'';var documentName=String(data.documentName||'').trim(),documentUrl=String(data.documentUrl||'').trim(),documentId=oldId; if(data.base64&&data.fileName){if(oldId){try{DriveApp.getFileById(oldId).setTrashed(true);}catch(e){}}var bytes=Utilities.base64Decode(data.base64);if(bytes.length>10*1024*1024)throw new Error('El documento supera 10 MB.');var file=getDriveFolder_().createFile(Utilities.newBlob(bytes,data.mimeType||'application/octet-stream',data.fileName));file.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW);documentId=file.getId();documentName=data.fileName;documentUrl='https://drive.google.com/uc?export=download&id='+documentId;}var created=row<=s.getLastRow()?String(s.getRange(row,13).getDisplayValue()||''):'';if(!created)created=new Date().toISOString();s.getRange(row,1,1,13).setValues([[id,title,date,String(data.time||'').trim(),String(data.place||'').trim(),String(data.city||'').trim(),String(data.description||'').trim(),String(data.url||'').trim(),documentName,documentUrl,documentId,data.published===false?'No':'Sí',created]]);return{ok:true,id:id};}
function deleteNews(data){assertAdmin_(data&&data.password);return deleteRowById_('NoticiasWeb',data.id);}
function deleteEvent(data){assertAdmin_(data&&data.password);var s=getOrCreateSheet_('EventosWeb',eventHeaders_()),row=findRowById_(s,data.id);if(row<0)throw new Error('Evento no encontrado.');var fid=String(s.getRange(row,11).getDisplayValue()||'');if(fid){try{DriveApp.getFileById(fid).setTrashed(true);}catch(e){}}s.deleteRow(row);return{ok:true};}
function deleteResource(data){assertAdmin_(data&&data.password);var s=getOrCreateSheet_('RecursosWeb',['id','titulo','categoria','descripcion','archivo','url','creado']),row=findRowById_(s,data.id);if(row<0)throw new Error('Recurso no encontrado.');var url=String(s.getRange(row,6).getDisplayValue());var m=url.match(/id=([^&]+)/);if(m){try{DriveApp.getFileById(m[1]).setTrashed(true);}catch(e){}}s.deleteRow(row);return{ok:true};}
function deleteRowById_(name,id){var s=getOrCreateSheet_(name,[]),row=findRowById_(s,id);if(row<0)throw new Error('Registro no encontrado.');s.deleteRow(row);return{ok:true};}
function setPublished_(data){assertAdmin_(data&&data.password);var s=getOrCreateSheet_('PropuestasWeb',proposalHeaders_()),row=findRowById_(s,data.id);if(row<0)throw new Error('Propuesta no encontrada.');s.getRange(row,7).setValue(data.published?'Sí':'No');return{ok:true};}
function deleteProposal(data){assertAdmin_(data&&data.password);return deleteRowById_('PropuestasWeb',data.id);}
function saveProposalPublic_(data){var type=data.type==='cancion'||data.type==='frase'?data.type:'';if(!type)throw new Error('Tipo no válido.');var s=getOrCreateSheet_('PropuestasWeb',proposalHeaders_());s.appendRow([Utilities.getUuid(),type,String(data.title||'').slice(0,200),String(data.artist||'').slice(0,160),String(data.text||'').slice(0,1000),String(data.proposer||'').slice(0,120),'No',new Date().toISOString()]);return{ok:true,message:'Propuesta recibida. Quedará pendiente de revisión.'};}
function assertAdmin_(password){var expected=PropertiesService.getScriptProperties().getProperty('BACKOFFICE_PASSWORD');if(!expected)throw new Error('El backoffice aún no tiene contraseña configurada.');if(String(password||'')!==expected)throw new Error('Contraseña incorrecta.');}
