/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccesibilidadRouteImport } from './routes/accesibilidad'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DatosRouteImport } from './routes/datos'
import { Route as EntidadesRouteImport } from './routes/entidades'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as ImagenPerfilRouteImport } from './routes/imagen-perfil'
import { Route as LaDependenciaRouteImport } from './routes/la-dependencia'
import { Route as LaPlataformaRouteImport } from './routes/la-plataforma'
import { Route as NovedadesRouteImport } from './routes/novedades'
import { Route as PrensaRouteImport } from './routes/prensa'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as RedesSocialesRouteImport } from './routes/redes-sociales'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TestimoniosRouteImport } from './routes/testimonios'
import { Route as UneteRouteImport } from './routes/unete'
import { Route as VoluntariadoRouteImport } from './routes/voluntariado'
import { Route as ApiCmsRouteImport } from './routes/api/cms'
import { Route as MocionesAyuntamientosRouteImport } from './routes/mociones-ayuntamientos'
import { Route as ApiMocionesMunicipiosRouteImport } from './routes/api/mociones-municipios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesibilidadRoute = AccesibilidadRouteImport.update({
  id: '/accesibilidad',
  path: '/accesibilidad',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DatosRoute = DatosRouteImport.update({
  id: '/datos',
  path: '/datos',
  getParentRoute: () => rootRouteImport,
} as any)
const EntidadesRoute = EntidadesRouteImport.update({
  id: '/entidades',
  path: '/entidades',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagenPerfilRoute = ImagenPerfilRouteImport.update({
  id: '/imagen-perfil',
  path: '/imagen-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LaDependenciaRoute = LaDependenciaRouteImport.update({
  id: '/la-dependencia',
  path: '/la-dependencia',
  getParentRoute: () => rootRouteImport,
} as any)
const LaPlataformaRoute = LaPlataformaRouteImport.update({
  id: '/la-plataforma',
  path: '/la-plataforma',
  getParentRoute: () => rootRouteImport,
} as any)
const NovedadesRoute = NovedadesRouteImport.update({
  id: '/novedades',
  path: '/novedades',
  getParentRoute: () => rootRouteImport,
} as any)
const PrensaRoute = PrensaRouteImport.update({
  id: '/prensa',
  path: '/prensa',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const RedesSocialesRoute = RedesSocialesRouteImport.update({
  id: '/redes-sociales',
  path: '/redes-sociales',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimoniosRoute = TestimoniosRouteImport.update({
  id: '/testimonios',
  path: '/testimonios',
  getParentRoute: () => rootRouteImport,
} as any)
const UneteRoute = UneteRouteImport.update({
  id: '/unete',
  path: '/unete',
  getParentRoute: () => rootRouteImport,
} as any)
const VoluntariadoRoute = VoluntariadoRouteImport.update({
  id: '/voluntariado',
  path: '/voluntariado',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsRoute = ApiCmsRouteImport.update({
  id: '/api/cms',
  path: '/api/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const MocionesAyuntamientosRoute = MocionesAyuntamientosRouteImport.update({
  id: '/mociones-ayuntamientos',
  path: '/mociones-ayuntamientos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMocionesMunicipiosRoute = ApiMocionesMunicipiosRouteImport.update({
  id: '/api/mociones-municipios',
  path: '/api/mociones-municipios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/mociones-ayuntamientos': typeof MocionesAyuntamientosRoute
  '/api/mociones-municipios': typeof ApiMocionesMunicipiosRoute
  '/': typeof IndexRoute
  '/accesibilidad': typeof AccesibilidadRoute
  '/admin': typeof AdminRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/datos': typeof DatosRoute
  '/entidades': typeof EntidadesRoute
  '/eventos': typeof EventosRoute
  '/imagen-perfil': typeof ImagenPerfilRoute
  '/la-dependencia': typeof LaDependenciaRoute
  '/la-plataforma': typeof LaPlataformaRoute
  '/novedades': typeof NovedadesRoute
  '/prensa': typeof PrensaRoute
  '/privacidad': typeof PrivacidadRoute
  '/redes-sociales': typeof RedesSocialesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonios': typeof TestimoniosRoute
  '/unete': typeof UneteRoute
  '/voluntariado': typeof VoluntariadoRoute
  '/api/cms': typeof ApiCmsRoute
}
export interface FileRoutesByTo {
  '/mociones-ayuntamientos': typeof MocionesAyuntamientosRoute
  '/api/mociones-municipios': typeof ApiMocionesMunicipiosRoute
  '/': typeof IndexRoute
  '/accesibilidad': typeof AccesibilidadRoute
  '/admin': typeof AdminRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/datos': typeof DatosRoute
  '/entidades': typeof EntidadesRoute
  '/eventos': typeof EventosRoute
  '/imagen-perfil': typeof ImagenPerfilRoute
  '/la-dependencia': typeof LaDependenciaRoute
  '/la-plataforma': typeof LaPlataformaRoute
  '/novedades': typeof NovedadesRoute
  '/prensa': typeof PrensaRoute
  '/privacidad': typeof PrivacidadRoute
  '/redes-sociales': typeof RedesSocialesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonios': typeof TestimoniosRoute
  '/unete': typeof UneteRoute
  '/voluntariado': typeof VoluntariadoRoute
  '/api/cms': typeof ApiCmsRoute
}
export interface FileRoutesById {
  '/mociones-ayuntamientos': typeof MocionesAyuntamientosRoute
  '/api/mociones-municipios': typeof ApiMocionesMunicipiosRoute
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accesibilidad': typeof AccesibilidadRoute
  '/admin': typeof AdminRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/datos': typeof DatosRoute
  '/entidades': typeof EntidadesRoute
  '/eventos': typeof EventosRoute
  '/imagen-perfil': typeof ImagenPerfilRoute
  '/la-dependencia': typeof LaDependenciaRoute
  '/la-plataforma': typeof LaPlataformaRoute
  '/novedades': typeof NovedadesRoute
  '/prensa': typeof PrensaRoute
  '/privacidad': typeof PrivacidadRoute
  '/redes-sociales': typeof RedesSocialesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonios': typeof TestimoniosRoute
  '/unete': typeof UneteRoute
  '/voluntariado': typeof VoluntariadoRoute
  '/api/cms': typeof ApiCmsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/mociones-ayuntamientos'
    | '/api/mociones-municipios'
    | '/'
    | '/accesibilidad'
    | '/admin'
    | '/aviso-legal'
    | '/contacto'
    | '/cookies'
    | '/datos'
    | '/entidades'
    | '/eventos'
    | '/imagen-perfil'
    | '/la-dependencia'
    | '/la-plataforma'
    | '/novedades'
    | '/prensa'
    | '/privacidad'
    | '/redes-sociales'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/testimonios'
    | '/unete'
    | '/voluntariado'
    | '/api/cms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/mociones-ayuntamientos'
    | '/api/mociones-municipios'
    | '/'
    | '/accesibilidad'
    | '/admin'
    | '/aviso-legal'
    | '/contacto'
    | '/cookies'
    | '/datos'
    | '/entidades'
    | '/eventos'
    | '/imagen-perfil'
    | '/la-dependencia'
    | '/la-plataforma'
    | '/novedades'
    | '/prensa'
    | '/privacidad'
    | '/redes-sociales'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/testimonios'
    | '/unete'
    | '/voluntariado'
    | '/api/cms'
  id:
    | '/mociones-ayuntamientos'
    | '/api/mociones-municipios'
    | '__root__'
    | '/'
    | '/accesibilidad'
    | '/admin'
    | '/aviso-legal'
    | '/contacto'
    | '/cookies'
    | '/datos'
    | '/entidades'
    | '/eventos'
    | '/imagen-perfil'
    | '/la-dependencia'
    | '/la-plataforma'
    | '/novedades'
    | '/prensa'
    | '/privacidad'
    | '/redes-sociales'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/testimonios'
    | '/unete'
    | '/voluntariado'
    | '/api/cms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesibilidadRoute: typeof AccesibilidadRoute
  AdminRoute: typeof AdminRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  ContactoRoute: typeof ContactoRoute
  CookiesRoute: typeof CookiesRoute
  DatosRoute: typeof DatosRoute
  EntidadesRoute: typeof EntidadesRoute
  EventosRoute: typeof EventosRoute
  ImagenPerfilRoute: typeof ImagenPerfilRoute
  LaDependenciaRoute: typeof LaDependenciaRoute
  LaPlataformaRoute: typeof LaPlataformaRoute
  NovedadesRoute: typeof NovedadesRoute
  PrensaRoute: typeof PrensaRoute
  PrivacidadRoute: typeof PrivacidadRoute
  RedesSocialesRoute: typeof RedesSocialesRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestimoniosRoute: typeof TestimoniosRoute
  UneteRoute: typeof UneteRoute
  VoluntariadoRoute: typeof VoluntariadoRoute
  ApiCmsRoute: typeof ApiCmsRoute
}  MocionesAyuntamientosRoute: typeof MocionesAyuntamientosRoute
  ApiMocionesMunicipiosRoute: typeof ApiMocionesMunicipiosRoute


declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accesibilidad': {
      id: '/accesibilidad'
      path: '/accesibilidad'
      fullPath: '/accesibilidad'
      preLoaderRoute: typeof AccesibilidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datos': {
      id: '/datos'
      path: '/datos'
      fullPath: '/datos'
      preLoaderRoute: typeof DatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entidades': {
      id: '/entidades'
      path: '/entidades'
      fullPath: '/entidades'
      preLoaderRoute: typeof EntidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imagen-perfil': {
      id: '/imagen-perfil'
      path: '/imagen-perfil'
      fullPath: '/imagen-perfil'
      preLoaderRoute: typeof ImagenPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/la-dependencia': {
      id: '/la-dependencia'
      path: '/la-dependencia'
      fullPath: '/la-dependencia'
      preLoaderRoute: typeof LaDependenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/la-plataforma': {
      id: '/la-plataforma'
      path: '/la-plataforma'
      fullPath: '/la-plataforma'
      preLoaderRoute: typeof LaPlataformaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novedades': {
      id: '/novedades'
      path: '/novedades'
      fullPath: '/novedades'
      preLoaderRoute: typeof NovedadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prensa': {
      id: '/prensa'
      path: '/prensa'
      fullPath: '/prensa'
      preLoaderRoute: typeof PrensaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redes-sociales': {
      id: '/redes-sociales'
      path: '/redes-sociales'
      fullPath: '/redes-sociales'
      preLoaderRoute: typeof RedesSocialesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonios': {
      id: '/testimonios'
      path: '/testimonios'
      fullPath: '/testimonios'
      preLoaderRoute: typeof TestimoniosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unete': {
      id: '/unete'
      path: '/unete'
      fullPath: '/unete'
      preLoaderRoute: typeof UneteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voluntariado': {
      id: '/voluntariado'
      path: '/voluntariado'
      fullPath: '/voluntariado'
      preLoaderRoute: typeof VoluntariadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms': {
      id: '/api/cms'
      path: '/api/cms'
      fullPath: '/api/cms'
      preLoaderRoute: typeof ApiCmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mociones-ayuntamientos': {
      id: '/mociones-ayuntamientos'
      path: '/mociones-ayuntamientos'
      fullPath: '/mociones-ayuntamientos'
      preLoaderRoute: typeof MocionesAyuntamientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mociones-municipios': {
      id: '/api/mociones-municipios'
      path: '/api/mociones-municipios'
      fullPath: '/api/mociones-municipios'
      preLoaderRoute: typeof ApiMocionesMunicipiosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesibilidadRoute: AccesibilidadRoute,
  AdminRoute: AdminRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  ContactoRoute: ContactoRoute,
  CookiesRoute: CookiesRoute,
  DatosRoute: DatosRoute,
  EntidadesRoute: EntidadesRoute,
  EventosRoute: EventosRoute,
  ImagenPerfilRoute: ImagenPerfilRoute,
  LaDependenciaRoute: LaDependenciaRoute,
  LaPlataformaRoute: LaPlataformaRoute,
  NovedadesRoute: NovedadesRoute,
  PrensaRoute: PrensaRoute,
  PrivacidadRoute: PrivacidadRoute,
  RedesSocialesRoute: RedesSocialesRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestimoniosRoute: TestimoniosRoute,
  UneteRoute: UneteRoute,
  VoluntariadoRoute: VoluntariadoRoute,
  ApiCmsRoute: ApiCmsRoute,
}  MocionesAyuntamientosRoute: MocionesAyuntamientosRoute,
  ApiMocionesMunicipiosRoute: ApiMocionesMunicipiosRoute,

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
